version: '3.8'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    image: drupal-app
    container_name: drupal_app
    volumes:
      - .:/var/www/html
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: password
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_web
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - drupal
      - db

  db:
    image: mysql:8.0
    container_name: drupal_db
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  db_data:
